### ISSUE TITLE
Graph not rendering if instance is running a container with no memory reserve set

### ISSUE THREAD

**Issue by kwilsonO** [ExpediaDotCom/c3vis#27]
https://github.com/ExpediaDotCom/c3vis/blob/da7d0244d36c3b44d40389b05688a46e9c73cdfc/public/javascripts/graph.js#L64

Not sure if this is specific to our use case, but we have a handful of containers that do not have a memory reserve set, for those the line referenced above returns NaN causing any bar that contains a container without a mem reserve set not to render.

I'm not a js developer but I was able to fix this by changing the above line to the following: 

`var resourceAllocation = task.taskDefinition.containerDefinitions.reduce(function (sum, b) { return sum + (resourceType == ResourceEnum.MEMORY ? ( isNaN(b.memory) || (b.memory == null) ? 0 : b.memory ) : b.cpu); }, 0);`

**Comment by mattcallanan** [comment]
Thanks @kwilsonO. 
Feel free to put together a Pull Request for this.

**Comment by mattcallanan** [comment]
@kwilsonO this should be fixed by [release 0.5.0](https://github.com/ExpediaDotCom/c3vis/releases/tag/0.5.0).

I'll close this issue for now, but let us know if not fixed and we can address.
